-- Track whether a bundle's name was autogenerated — i.e. taken from the dropped
-- archive at import time and never explicitly set by a person. A metadata import
-- (the scraped-metadata patch) may overwrite an autogenerated name with the real
-- title it carries, but must leave a name a user chose alone.
--
-- Default false: existing bundles are treated as user-owned, so a patch never
-- silently renames one. New imports set this to true when the name field was
-- left at the archive's name, and an explicit rename clears it.
ALTER TABLE bundles
    ADD COLUMN name_autogenerated boolean NOT NULL DEFAULT false;
