//! Apply a scraped bundle patch onto an existing
//! bundle: match each patch model to a member model, then merge metadata under
//! the caller's chosen rules. Two steps, like every other write in here —
//! `preview` returns the match diff to confirm, `apply` writes it.
//!
//! Generic on purpose: it knows the `meshtrove.bundle-patch/1` schema, not Loot.
//! The upload is the scraper's zip — `{ patch.json, images/* }`. The format and
//! these merge rules are specified in `docs/bundle-patch.md` — keep it true.

use std::collections::HashMap;
use std::io::{Cursor, Read};

use axum::{
    Json, Router,
    extract::{DefaultBodyLimit, Multipart, Path, State},
    routing::post,
};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use uuid::Uuid;

use crate::error::ApiError;
use crate::extractors::User;
use crate::routes::custom_fields::{
    CustomField, Resolved, ValueOwner, apply_patch_values, fields_by_key, persist_bundle_fields,
    resolve_patch_value,
};
use crate::routes::tags::upsert_tag;
use crate::services::blobstore::BlobStore;
use crate::state::AppState;

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/api/bundles/{id}/patch/preview", post(preview))
        .route("/api/bundles/{id}/patch", post(apply))
        .route("/api/models/{id}/patch/preview", post(model_preview))
        .route("/api/models/{id}/patch", post(model_apply))
        // The zip carries images; the store streams, so no body cap.
        .layer(DefaultBodyLimit::disable())
}

// ---------------------------------------------------------------------------
// The patch document — only the fields we read; everything else is ignored, so
// a richer patch from some future scraper still applies.
// ---------------------------------------------------------------------------

#[derive(Deserialize, Default)]
struct Patch {
    #[serde(default)]
    source: PatchSource,
    #[serde(default)]
    bundle: PatchBundle,
    #[serde(default)]
    models: Vec<PatchModel>,
}

/// Where the scrape came from. Only `url` interests us — the page the bundle was
/// bought/scraped from, which we stamp onto member models that have no source.
#[derive(Deserialize, Default)]
struct PatchSource {
    #[serde(default)]
    url: Option<String>,
}

#[derive(Deserialize, Default)]
struct PatchBundle {
    /// The bundle's real title from the scrape. Replaces the bundle's name only
    /// if that name was autogenerated (the archive's, never set by a user).
    #[serde(default)]
    name: Option<String>,
    /// The site/author the bundle came from, by name — resolved to a `creators`
    /// row and stamped onto member models that have no creator yet.
    #[serde(default)]
    creator: Option<String>,
    #[serde(default)]
    description_md: Option<String>,
    /// Candidate covers, primary first (relative paths into the zip).
    #[serde(default)]
    images: Vec<String>,
    /// Admin-defined extra metadata, by field key. A key the vocabulary doesn't
    /// know is a warning in the preview, never an error — a scrape carries
    /// whatever the shop page had.
    #[serde(default)]
    custom_fields: HashMap<String, serde_json::Value>,
}

#[derive(Deserialize, Default)]
struct PatchModel {
    /// The library model this entry *is*, when the scraper already knows —
    /// the strongest match signal, consulted before any name matching. Lenient
    /// on the way in: `""` (a hand-fill file's unmatched rows) reads as absent.
    #[serde(default, deserialize_with = "de_opt_uuid")]
    uuid: Option<Uuid>,
    #[serde(default, rename = "match")]
    match_hint: MatchHint,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    tags: Vec<String>,
    /// Model description (markdown) — becomes a new description revision on
    /// the matched model when the apply opts in.
    #[serde(default)]
    description_md: Option<String>,
    /// Relative path into the zip, or null. One image; `images` carries a whole
    /// gallery. Kept because every patch written before `images` existed uses it.
    #[serde(default)]
    image: Option<String>,
    /// A gallery for this model, primary first — the shop-page equivalent of
    /// `bundle.images`. Additive within `/1`: a patch may send `image`, `images`,
    /// or both, and a consumer that predates this field still reads `image`.
    #[serde(default)]
    images: Vec<String>,
    /// The bundle category it came from (Heroes, Busts, …) — shown to tell two
    /// same-named models apart.
    #[serde(default)]
    category: Option<String>,
    /// This model's own page on the shop. A range sold as separate products has
    /// no single URL, so where the scraper knows the per-model one it beats the
    /// bundle-level `source.url` — see the apply below.
    #[serde(default)]
    source_url: Option<String>,
    /// The creator's own id/SKU for this model — Fat Dragon's `FDG0250`,
    /// a publisher's product code. Lands in `models.creator_ref`, the same
    /// column a carve layout fills from a `creator_ref` capture group.
    #[serde(default)]
    source_ref: Option<String>,
    /// Admin-defined extra metadata for this model, by field key. Same lenient
    /// rule as the bundle's.
    #[serde(default)]
    custom_fields: HashMap<String, serde_json::Value>,
}

/// An optional uuid that tolerates `""`/whitespace as "not given" — annotated
/// scraper files keep the field on every row and blank it where unknown.
fn de_opt_uuid<'de, D: serde::Deserializer<'de>>(d: D) -> Result<Option<Uuid>, D::Error> {
    let s: Option<String> = Option::deserialize(d)?;
    match s.as_deref().map(str::trim) {
        None | Some("") => Ok(None),
        Some(v) => Uuid::parse_str(v)
            .map(Some)
            .map_err(serde::de::Error::custom),
    }
}

#[derive(Deserialize, Default)]
struct MatchHint {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    aliases: Vec<String>,
}

impl PatchModel {
    /// The label the UI and the options map key this model by: its rename target,
    /// else its match name.
    fn label(&self) -> String {
        self.name
            .clone()
            .or_else(|| self.match_hint.name.clone())
            .unwrap_or_default()
    }
    /// Every image this model carries, in the order they should be applied —
    /// the singular `image` first, then `images`, deduped by path. A patch that
    /// sends the same file as both (a scraper keeping `image` populated for
    /// older consumers) contributes it once, and it stays primary.
    fn image_paths(&self) -> Vec<&str> {
        let mut paths: Vec<&str> = Vec::new();
        for p in self.image.iter().chain(self.images.iter()) {
            let p = p.as_str();
            if !p.is_empty() && !paths.contains(&p) {
                paths.push(p);
            }
        }
        paths
    }
    /// Every spelling that could match a library model.
    fn match_keys(&self) -> Vec<String> {
        let mut keys: Vec<String> = Vec::new();
        for s in self
            .name
            .iter()
            .chain(self.match_hint.name.iter())
            .chain(self.match_hint.aliases.iter())
        {
            let k = normalize(s);
            if !k.is_empty() && !keys.contains(&k) {
                keys.push(k);
            }
        }
        keys
    }
    /// Each spelling as an ordered list of words, for the prefix fallback: a
    /// member whose whole name is the leading run here (`Crocodile` in `Crocodile
    /// Buried Tomb`) is a match even though the collapsed strings differ.
    fn word_spellings(&self) -> Vec<Vec<String>> {
        self.name
            .iter()
            .chain(self.match_hint.name.iter())
            .chain(self.match_hint.aliases.iter())
            .map(|s| words(s))
            .filter(|w| !w.is_empty())
            .collect()
    }
}

/// Collapse camel case, spaces, underscores and hyphens to nothing, lowercased —
/// so the scraper's "Warrior Mummy" matches the carve's "WarriorMummy" folder
/// model without either side having to guess the other's spelling.
fn normalize(s: &str) -> String {
    s.chars()
        .filter(|c| c.is_alphanumeric())
        .flat_map(|c| c.to_lowercase())
        .collect()
}

/// The same name split into its words, in order (`AdvisorMummy` → `["advisor",
/// "mummy"]`): `expand_camel_case` puts the spaces back, then we lowercase and
/// split on anything non-alphanumeric. Ordered, unlike `normalize`, so a prefix
/// match can tell that "Crocodile Buried Tomb" *starts with* "Crocodile".
fn words(s: &str) -> Vec<String> {
    crate::util::expand_camel_case(s)
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(str::to_lowercase)
        .collect()
}

// ---------------------------------------------------------------------------
// Reading the zip out of the multipart body.
// ---------------------------------------------------------------------------

struct Archive {
    patch: Patch,
    images: HashMap<String, Vec<u8>>,
}

/// A multipart body: every `file` field, plus the `options` text field if the
/// caller sent one (apply does, preview doesn't).
struct Upload {
    options: Option<String>,
    files: Vec<(String, Vec<u8>)>,
}

async fn read_upload(mut multipart: Multipart) -> Result<Upload, ApiError> {
    let mut upload = Upload {
        options: None,
        files: Vec::new(),
    };
    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|e| ApiError::BadRequest(format!("bad multipart body: {e}")))?
    {
        match field.name() {
            Some("options") => {
                upload.options = Some(
                    field
                        .text()
                        .await
                        .map_err(|e| ApiError::BadRequest(format!("bad options field: {e}")))?,
                );
            }
            // Repeatable. One drop of six per-model patch zips is six `file`
            // parts, and they merge into a single logical patch below.
            Some("file") => {
                let name = field.file_name().unwrap_or_default().to_string();
                let bytes = field
                    .bytes()
                    .await
                    .map_err(|e| ApiError::BadRequest(format!("reading upload: {e}")))?
                    .to_vec();
                upload.files.push((name, bytes));
            }
            _ => {}
        }
    }
    if upload.files.is_empty() {
        return Err(ApiError::BadRequest("no file field in upload".into()));
    }
    Ok(upload)
}

/// One file's contribution, for the preview's benefit — a six-zip drop should
/// say which six and what each brought.
#[derive(Serialize, ToSchema)]
struct PatchFileRow {
    name: String,
    models: usize,
}

/// Read every uploaded zip and merge them into one logical patch.
///
/// The point is that per-model patches compose: `fdg-scrape` emits one zip per
/// product page, and dropping six of them on a bundle should behave exactly
/// like dropping one six-model zip. Nothing here changes what a single file
/// means — one file in gives one archive out, unchanged.
///
/// **Order is by filename, not arrival.** `key` — a patch model's index in the
/// merged `models[]` — is the identity the preview reports and the apply
/// options refer back to, so it has to be the same in both calls. Sorting means
/// that holds even if the two requests enumerate the same files in a different
/// order, which a drag-and-drop of a multi-file selection does not promise.
/// Duplicate filenames keep their arrival order relative to each other (the
/// sort is stable), so the client contract is only "send the same files".
///
/// Bundle-level fields are **first non-empty wins**, per field. In practice
/// per-model patches carry nothing but `bundle.creator` and they all agree; the
/// rule matters when one file in the drop is a deliberate bundle-cover patch
/// (ps-scrape's second button) and the rest are models — then that file
/// supplies name/description/cover whatever position it lands in.
async fn read_merged(
    files: Vec<(String, Vec<u8>)>,
) -> Result<(Archive, Vec<PatchFileRow>), ApiError> {
    let mut files = files;
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let mut merged = Archive {
        patch: Patch::default(),
        images: HashMap::new(),
    };
    let mut rows = Vec::new();
    let mut seen_cover_paths: Vec<String> = Vec::new();

    for (i, (name, bytes)) in files.into_iter().enumerate() {
        let archive = read_archive_from_bytes(bytes)
            .await
            // Which of six zips was the bad one is the only thing you want to
            // know here, and the inner error never says.
            .map_err(|e| match e {
                ApiError::BadRequest(m) => ApiError::BadRequest(format!("{name}: {m}")),
                other => other,
            })?;
        let Archive { mut patch, images } = archive;

        // Namespace every image path by the file's position, and rewrite this
        // patch's references to match, before anything is concatenated. Two
        // scrapers independently emitting `images/00.jpg` is not a collision
        // worth losing an image to — and it is the default case, since entry
        // names are per-zip and nothing coordinates them.
        //
        // Prefixing with an index that is unique per archive cannot itself
        // collide: two rewritten paths differ in their first segment unless
        // they came from the same file, where they were already distinct.
        let qualify = |path: &str| format!("{i}/{path}");
        for path in patch.bundle.images.iter_mut() {
            *path = qualify(path);
        }
        for m in patch.models.iter_mut() {
            if let Some(p) = m.image.as_mut() {
                *p = qualify(p);
            }
            for p in m.images.iter_mut() {
                *p = qualify(p);
            }
        }
        for (path, bytes) in images {
            merged.images.insert(qualify(&path), bytes);
        }

        rows.push(PatchFileRow {
            name,
            models: patch.models.len(),
        });

        // First non-empty wins, field by field.
        let b = &mut merged.patch.bundle;
        if b.name.is_none() {
            b.name = patch.bundle.name.take();
        }
        if b.creator.is_none() {
            b.creator = patch.bundle.creator.take();
        }
        if b.description_md.is_none() {
            b.description_md = patch.bundle.description_md.take();
        }
        if merged.patch.source.url.is_none() {
            merged.patch.source.url = patch.source.url.take();
        }
        for (key, value) in patch.bundle.custom_fields {
            merged
                .patch
                .bundle
                .custom_fields
                .entry(key)
                .or_insert(value);
        }
        // Covers concatenate rather than first-wins: `bundle.images` is
        // documented as "all added, the first becomes primary", so appending
        // keeps that meaning across files. Deduped by path so re-dropping the
        // same file twice doesn't queue the same cover twice.
        for path in patch.bundle.images {
            if !seen_cover_paths.contains(&path) {
                seen_cover_paths.push(path.clone());
                merged.patch.bundle.images.push(path);
            }
        }

        merged.patch.models.extend(patch.models);
    }

    Ok((merged, rows))
}

// ---------------------------------------------------------------------------
// Matching: patch models against the bundle's members.
// ---------------------------------------------------------------------------

struct Member {
    id: Uuid,
    name: String,
    tags: Vec<String>,
    /// Other names this model already answers to (from earlier imports/renames);
    /// extra lookup keys so a scrape that uses one of them still resolves.
    aliases: Vec<String>,
}

async fn bundle_members(state: &AppState, bundle_id: Uuid) -> Result<Vec<Member>, ApiError> {
    let rows = sqlx::query!(
        r#"SELECT m.id, m.name,
                  coalesce((SELECT array_agg(t.name::text ORDER BY t.name) FROM model_tags mt
                            JOIN tags t ON t.id = mt.tag_id WHERE mt.model_id = m.id), '{}')
                      as "tags!: Vec<String>",
                  coalesce((SELECT array_agg(a.alias::text ORDER BY a.alias)
                            FROM model_aliases a WHERE a.model_id = m.id), '{}')
                      as "aliases!: Vec<String>"
           FROM models m JOIN bundle_models bm ON bm.model_id = m.id
           WHERE bm.bundle_id = $1
           ORDER BY m.name"#,
        bundle_id,
    )
    .fetch_all(&state.db)
    .await?;
    Ok(rows
        .into_iter()
        .map(|r| Member {
            id: r.id,
            name: r.name,
            tags: r.tags,
            aliases: r.aliases,
        })
        .collect())
}

/// For each patch model, the member ids it could be. 0 = unmatched, 1 = matched,
/// >1 = ambiguous (the user picks).
///
/// Two tiers. First an exact match on the collapsed name, so a clean
/// "Advisor Mummy" always wins its `AdvisorMummy` folder outright. Only when that
/// finds nothing do we fall back to a prefix match: the scraped name usually
/// leads with the model and trails the bundle or category it came from
/// ("Crocodile Buried Tomb"), so a member whose whole name is the leading run of
/// words is a candidate. If several members prefix-match we keep the longest
/// (most specific) one, and if still tied use the scraped `category` — carried as
/// a tag on the model it belongs to — to break it.
///
/// Both tiers consider each member's stored aliases alongside its name, so a
/// model that a past import taught an alternate name still resolves by it.
fn resolve(patch: &Patch, members: &[Member]) -> Vec<Vec<Uuid>> {
    // Every name a member answers to, as a word list, for the prefix tier.
    let member_spellings: Vec<Vec<Vec<String>>> = members
        .iter()
        .map(|m| {
            std::iter::once(&m.name)
                .chain(m.aliases.iter())
                .map(|s| words(s))
                .filter(|w| !w.is_empty())
                .collect()
        })
        .collect();

    let mut by_key: HashMap<String, Vec<Uuid>> = HashMap::new();
    for m in members {
        for name in std::iter::once(&m.name).chain(m.aliases.iter()) {
            let key = normalize(name);
            if key.is_empty() {
                continue;
            }
            let ids = by_key.entry(key).or_default();
            if !ids.contains(&m.id) {
                ids.push(m.id);
            }
        }
    }

    patch
        .models
        .iter()
        .map(|pm| {
            // Tier 0: an explicit uuid is the patch pointing at the member
            // itself — it decides alone, names never overrule it. A uuid that
            // is not a member of this bundle matches *nothing* rather than
            // falling back to name guessing: the id says the scraper meant one
            // specific model, and that model isn't here.
            if let Some(id) = pm.uuid {
                return if members.iter().any(|m| m.id == id) {
                    vec![id]
                } else {
                    Vec::new()
                };
            }

            // Tier 1: exact on the collapsed name (or any alias).
            let mut ids: Vec<Uuid> = Vec::new();
            for key in pm.match_keys() {
                for id in by_key.get(&key).into_iter().flatten() {
                    if !ids.contains(id) {
                        ids.push(*id);
                    }
                }
            }
            if !ids.is_empty() {
                return ids;
            }

            // Tier 2: prefix fallback. A member matches if any of its spellings is
            // the leading run of a scraped spelling; its "length" for the
            // most-specific test is that of the longest such spelling.
            let scraped = pm.word_spellings();
            let matched_len = |i: usize| -> usize {
                member_spellings[i]
                    .iter()
                    .filter(|w| scraped.iter().any(|s| s.starts_with(w)))
                    .map(|w| w.len())
                    .max()
                    .unwrap_or(0)
            };
            let mut cands: Vec<usize> =
                (0..members.len()).filter(|&i| matched_len(i) > 0).collect();

            // Prefer the most specific: the longest name that still fits, so
            // "WarriorMummy" beats a bare "Warrior".
            if cands.len() > 1 {
                let longest = cands.iter().map(|&i| matched_len(i)).max().unwrap_or(0);
                cands.retain(|&i| matched_len(i) == longest);
            }

            // Still tied: the scraped category (Enemies, NPCs, …) rides along as a
            // tag on the model it belongs to. Narrow to members carrying it — but
            // only if that leaves at least one, so a category no member happens to
            // tag doesn't wipe out an otherwise-good set.
            if cands.len() > 1
                && let Some(cat) = pm
                    .category
                    .as_deref()
                    .map(str::trim)
                    .filter(|c| !c.is_empty())
            {
                let by_cat: Vec<usize> = cands
                    .iter()
                    .copied()
                    .filter(|&i| members[i].tags.iter().any(|t| t.eq_ignore_ascii_case(cat)))
                    .collect();
                if !by_cat.is_empty() {
                    cands = by_cat;
                }
            }

            cands.into_iter().map(|i| members[i].id).collect()
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Preview.
// ---------------------------------------------------------------------------

#[derive(Serialize, ToSchema)]
struct PatchPreview {
    /// The bundle description the patch carries, verbatim (markdown), or null.
    bundle_description: Option<String>,
    /// Candidate covers as `data:` URLs, primary first — so the UI shows the
    /// actual pictures, not just a count.
    bundle_covers: Vec<String>,
    matched: Vec<MatchedRow>,
    ambiguous: Vec<UnresolvedRow>,
    /// Patch models that matched no member automatically — the user can still
    /// pick a member for these by hand (that is what `members` is for).
    unmatched_patch: Vec<UnresolvedRow>,
    /// Members the patch said nothing about (left untouched).
    unmatched_members: Vec<String>,
    /// Every member of the bundle, with its current tags — so the UI can offer a
    /// manual match and show, per candidate, what it already has.
    members: Vec<Candidate>,
    /// Custom field values the patch carries that will be written.
    custom_fields_applied: usize,
    /// ...and the ones that won't, each with why. Never fatal: a scrape carries
    /// whatever the shop page had, and the user decides whether it matters.
    custom_field_warnings: Vec<CustomFieldWarning>,
    /// The uploaded files this preview merged, in the order their models were
    /// numbered — so a multi-file drop can show what it actually read.
    files: Vec<PatchFileRow>,
}

/// One scraped metadata key that will be skipped, and why.
#[derive(Serialize, ToSchema)]
struct CustomFieldWarning {
    /// "the bundle", or the patch model's label — where the key came from.
    source: String,
    key: String,
    reason: String,
}

/// Walk the patch's `custom_fields` — the bundle's plus each targeted model's —
/// reporting what would be written and what would be skipped. Shared shape
/// between preview (which shows this) and apply (which acts on it).
fn survey_custom_fields(
    fields: &std::collections::HashMap<String, CustomField>,
    patch: &Patch,
    bundle_id: Uuid,
    targets: &[(usize, Uuid)],
) -> (usize, Vec<CustomFieldWarning>) {
    let mut applied = 0;
    let mut warnings = Vec::new();
    let mut survey =
        |source: String, owner: ValueOwner, pairs: &HashMap<String, serde_json::Value>| {
            let mut keys: Vec<&String> = pairs.keys().collect();
            keys.sort();
            for key in keys {
                match resolve_patch_value(fields, owner, key, &pairs[key]) {
                    Resolved::Value { .. } => applied += 1,
                    Resolved::Warning(reason) => warnings.push(CustomFieldWarning {
                        source: source.clone(),
                        key: key.clone(),
                        reason,
                    }),
                }
            }
        };
    survey(
        "the bundle".to_string(),
        ValueOwner::Bundle(bundle_id),
        &patch.bundle.custom_fields,
    );
    for (idx, model_id) in targets {
        let pm = &patch.models[*idx];
        survey(pm.label(), ValueOwner::Model(*model_id), &pm.custom_fields);
    }
    (applied, warnings)
}

#[derive(Serialize, ToSchema)]
struct MatchedRow {
    /// The patch model's index — its stable identity. Names are not unique (a
    /// "Mummy Lord" in Enemies and another in Busts), so the UI and the apply
    /// options key on this, not the name.
    key: usize,
    patch_name: String,
    model_id: Uuid,
    model_name: String,
    /// Tags the patch would add that the model does not already have.
    add_tags: Vec<String>,
    has_image: bool,
    /// The patch carries a description for this model.
    has_description: bool,
    category: Option<String>,
    /// The creator's own id/SKU the patch would write to `creator_ref`. Shown
    /// because it *replaces* what the model has, which is worth seeing before
    /// you agree to it.
    creator_ref: Option<String>,
}

/// A patch model with no single match — ambiguous or unmatched. Carries the
/// patch's own tags and image so the UI can show what *would* be applied once a
/// member is chosen (add-tags recomputed client-side against that member).
#[derive(Serialize, ToSchema)]
struct UnresolvedRow {
    key: usize,
    patch_name: String,
    patch_tags: Vec<String>,
    has_image: bool,
    /// The patch carries a description for this model.
    has_description: bool,
    category: Option<String>,
    /// Present for ambiguous rows (the members it could be); empty when the UI
    /// should offer the whole member list.
    candidates: Vec<Candidate>,
}

#[derive(Serialize, ToSchema)]
struct Candidate {
    id: Uuid,
    name: String,
    tags: Vec<String>,
    /// Other names this model already answers to. The UI uses them to skip
    /// offering a rename to a name the model is already known by.
    aliases: Vec<String>,
}

async fn preview(
    State(state): State<AppState>,
    user: User,
    Path(bundle_id): Path<Uuid>,
    multipart: Multipart,
) -> Result<Json<PatchPreview>, ApiError> {
    let created_by = bundle_created_by(&state, bundle_id).await?;
    user.require_can_edit(created_by)?;

    let (archive, files) = read_merged(read_upload(multipart).await?.files).await?;
    let members = bundle_members(&state, bundle_id).await?;
    let resolution = resolve(&archive.patch, &members);
    let member_of = |id: Uuid| members.iter().find(|m| m.id == id);

    let mut matched = Vec::new();
    let mut ambiguous = Vec::new();
    let mut unmatched_patch = Vec::new();
    let mut claimed: std::collections::HashSet<Uuid> = std::collections::HashSet::new();

    let candidate_of = |m: &Member| Candidate {
        id: m.id,
        name: m.name.clone(),
        tags: m.tags.iter().map(|t| t.to_lowercase()).collect(),
        aliases: m.aliases.clone(),
    };
    let patch_tags = |pm: &PatchModel| pm.tags.iter().map(|t| t.to_lowercase()).collect::<Vec<_>>();
    let has_image = |pm: &PatchModel| {
        pm.image_paths()
            .iter()
            .any(|p| archive.images.contains_key(*p))
    };
    let has_description = |pm: &PatchModel| {
        pm.description_md
            .as_deref()
            .is_some_and(|d| !d.trim().is_empty())
    };

    // A member is "contested" when it is the sole match of more than one patch
    // model — two patch entries named "Gold" (Heroes and Busts) both landing on a
    // single "Gold" member, say. Applying both would quietly overwrite one with
    // the other, so none of them auto-applies: each becomes a manual choice
    // offering just that member, and the user says which patch entry owns it.
    let mut sole_counts: HashMap<Uuid, usize> = HashMap::new();
    for ids in &resolution {
        if let [id] = ids.as_slice() {
            *sole_counts.entry(*id).or_default() += 1;
        }
    }

    for (key, (pm, ids)) in archive.patch.models.iter().zip(&resolution).enumerate() {
        match ids.as_slice() {
            [] => unmatched_patch.push(UnresolvedRow {
                key,
                patch_name: pm.label(),
                patch_tags: patch_tags(pm),
                has_image: has_image(pm),
                has_description: has_description(pm),
                category: pm.category.clone(),
                candidates: Vec::new(),
            }),
            [id] if sole_counts.get(id).copied().unwrap_or(0) > 1 => {
                claimed.insert(*id);
                ambiguous.push(UnresolvedRow {
                    key,
                    patch_name: pm.label(),
                    patch_tags: patch_tags(pm),
                    has_image: has_image(pm),
                    has_description: has_description(pm),
                    category: pm.category.clone(),
                    candidates: member_of(*id).map(candidate_of).into_iter().collect(),
                });
            }
            [id] => {
                claimed.insert(*id);
                let member = member_of(*id);
                let have: std::collections::HashSet<String> = member
                    .map(|m| m.tags.iter().map(|t| t.to_lowercase()).collect())
                    .unwrap_or_default();
                let add_tags = patch_tags(pm)
                    .into_iter()
                    .filter(|t| !have.contains(t))
                    .collect::<Vec<_>>();
                matched.push(MatchedRow {
                    key,
                    patch_name: pm.label(),
                    model_id: *id,
                    model_name: member.map(|m| m.name.clone()).unwrap_or_default(),
                    add_tags,
                    has_image: has_image(pm),
                    has_description: has_description(pm),
                    category: pm.category.clone(),
                    creator_ref: pm
                        .source_ref
                        .as_deref()
                        .map(str::trim)
                        .filter(|r| !r.is_empty())
                        .map(str::to_string),
                });
            }
            many => {
                for id in many {
                    claimed.insert(*id);
                }
                ambiguous.push(UnresolvedRow {
                    key,
                    patch_name: pm.label(),
                    patch_tags: patch_tags(pm),
                    has_image: has_image(pm),
                    has_description: has_description(pm),
                    category: pm.category.clone(),
                    candidates: many
                        .iter()
                        .filter_map(|id| member_of(*id))
                        .map(candidate_of)
                        .collect(),
                });
            }
        }
    }

    let unmatched_members = members
        .iter()
        .filter(|m| !claimed.contains(&m.id))
        .map(|m| m.name.clone())
        .collect();

    // Custom fields are surveyed against the rows that would auto-apply. A row
    // the user resolves by hand isn't known yet, so its metadata isn't counted
    // here — the apply writes it all the same.
    let auto_targets: Vec<(usize, Uuid)> = matched.iter().map(|r| (r.key, r.model_id)).collect();
    let (custom_fields_applied, custom_field_warnings) = survey_custom_fields(
        &fields_by_key(&mut *state.db.acquire().await?).await?,
        &archive.patch,
        bundle_id,
        &auto_targets,
    );

    Ok(Json(PatchPreview {
        custom_fields_applied,
        custom_field_warnings,
        files,
        bundle_description: archive
            .patch
            .bundle
            .description_md
            .clone()
            .filter(|d| !d.trim().is_empty()),
        bundle_covers: archive
            .patch
            .bundle
            .images
            .iter()
            .filter_map(|path| {
                let bytes = archive.images.get(path)?;
                let mime = mime_guess::from_path(path)
                    .first()
                    .map(|m| m.to_string())
                    .unwrap_or_else(|| "image/png".into());
                use base64::Engine;
                Some(format!(
                    "data:{mime};base64,{}",
                    base64::engine::general_purpose::STANDARD.encode(bytes)
                ))
            })
            .collect(),
        matched,
        ambiguous,
        unmatched_patch,
        unmatched_members,
        members: members.iter().map(candidate_of).collect(),
    }))
}

// ---------------------------------------------------------------------------
// Apply.
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize, Default, PartialEq, Clone, Copy)]
#[serde(rename_all = "snake_case")]
enum TagMode {
    #[default]
    Merge,
    Replace,
    Skip,
}

#[derive(Debug, Deserialize, Default, PartialEq, Clone, Copy)]
#[serde(rename_all = "snake_case")]
enum ImageMode {
    /// Drop the model's rendered previews and make the scraped image its picture.
    #[default]
    ReplaceGenerated,
    /// Keep the renders; add the scraped image and make it primary.
    Add,
    Skip,
}

#[derive(Deserialize, Default)]
struct ApplyOptions {
    /// Patch model *keys* (indices, as strings) whose matched model should be
    /// renamed to the scraped name. Per-model, not all-or-nothing — a rename is a
    /// bigger commitment than a tag. Keyed by index, not name: names are not unique.
    #[serde(default)]
    rename: Vec<String>,
    #[serde(default)]
    model_tags: TagMode,
    #[serde(default)]
    model_images: ImageMode,
    /// Insert each patch model's `description_md` as a new description
    /// revision on its matched model.
    #[serde(default)]
    model_descriptions: bool,
    #[serde(default)]
    bundle_cover: bool,
    #[serde(default)]
    bundle_description: bool,
    /// Resolves ambiguous/contested rows and adopts unmatched ones: patch model
    /// key (index, as a string) → the member id to apply it to. Overrides the
    /// automatic single match too.
    #[serde(default)]
    matches: HashMap<String, Uuid>,
}

#[derive(Serialize, ToSchema, Default)]
struct ApplyResult {
    models_updated: usize,
    images_added: usize,
    tags_added: usize,
    aliases_added: usize,
    descriptions_added: usize,
    /// Custom field values written, on the bundle and its members together.
    custom_fields_set: usize,
    /// Models whose `creator_ref` ("Creator ID") the patch set or corrected.
    creator_refs_set: usize,
}

/// A blob already put into the store, ready to become an image row.
struct StagedImage {
    sha256: String,
    size: i64,
    mime: String,
}

async fn stage_image(
    state: &AppState,
    images: &HashMap<String, Vec<u8>>,
    path: &str,
) -> Result<Option<StagedImage>, ApiError> {
    let Some(bytes) = images.get(path) else {
        return Ok(None);
    };
    let mime = mime_guess::from_path(path)
        .first()
        .map(|m| m.to_string())
        .unwrap_or_else(|| "image/png".into());
    let bytes = bytes.clone();
    let stream = futures::stream::once(async move { Ok(bytes::Bytes::from(bytes)) });
    let blob = state.store.put(Box::pin(stream)).await?;
    Ok(Some(StagedImage {
        sha256: blob.sha256,
        size: blob.size,
        mime,
    }))
}

#[tracing::instrument(skip_all, fields(bundle = %bundle_id))]
async fn apply(
    State(state): State<AppState>,
    user: User,
    Path(bundle_id): Path<Uuid>,
    multipart: Multipart,
) -> Result<Json<ApplyResult>, ApiError> {
    tracing::info!("patch apply: start");
    let created_by = bundle_created_by(&state, bundle_id).await?;
    user.require_can_edit(created_by)?;

    // options come as a text field alongside the file(s); read them together.
    let upload = read_upload(multipart).await?;
    let options: ApplyOptions = match upload.options.as_deref() {
        Some(text) => serde_json::from_str(text)
            .map_err(|e| ApiError::BadRequest(format!("bad options: {e}")))?,
        None => ApplyOptions::default(),
    };
    // Same merge as the preview, so `key` means the same thing in both — which
    // is what `options.rename` and `options.matches` are indexed by. Send the
    // same files and the numbering is identical; see `read_merged`.
    let (archive, _files) = read_merged(upload.files).await?;

    let members = bundle_members(&state, bundle_id).await?;
    let resolution = resolve(&archive.patch, &members);
    tracing::info!(
        patch_models = archive.patch.models.len(),
        members = members.len(),
        "patch apply: archive read, members fetched"
    );

    // A member contested by several patch models never auto-applies — the same
    // rule preview shows — so the two "Gold" entries cannot both silently land on
    // one model. Only an explicit `matches` entry resolves a contested one.
    let mut sole_counts: HashMap<Uuid, usize> = HashMap::new();
    for ids in &resolution {
        if let [id] = ids.as_slice() {
            *sole_counts.entry(*id).or_default() += 1;
        }
    }

    // Which member each patch model applies to: the caller's explicit choice
    // (keyed by index), else the automatic single, uncontested match.
    let mut targets: Vec<(usize, Uuid)> = Vec::new();
    for (idx, ids) in resolution.iter().enumerate() {
        let chosen =
            options
                .matches
                .get(&idx.to_string())
                .copied()
                .or_else(|| match ids.as_slice() {
                    [id] if sole_counts.get(id).copied().unwrap_or(0) == 1 => Some(*id),
                    _ => None,
                });
        if let Some(model_id) = chosen {
            targets.push((idx, model_id));
        }
    }

    // Put every image blob before opening the transaction — a blob put is async
    // filesystem work, and a rollback must not have to un-write the store.
    let mut model_images: HashMap<usize, Vec<StagedImage>> = HashMap::new();
    if options.model_images != ImageMode::Skip {
        for (idx, _) in &targets {
            let mut staged_all = Vec::new();
            for path in archive.patch.models[*idx].image_paths() {
                if let Some(staged) = stage_image(&state, &archive.images, path).await? {
                    staged_all.push(staged);
                }
            }
            if !staged_all.is_empty() {
                model_images.insert(*idx, staged_all);
            }
        }
    }
    let mut cover_images: Vec<StagedImage> = Vec::new();
    if options.bundle_cover {
        for path in &archive.patch.bundle.images {
            if let Some(staged) = stage_image(&state, &archive.images, path).await? {
                cover_images.push(staged);
            }
        }
    }

    let mut result = ApplyResult {
        models_updated: 0,
        images_added: 0,
        tags_added: 0,
        aliases_added: 0,
        descriptions_added: 0,
        custom_fields_set: 0,
        creator_refs_set: 0,
    };
    let custom_fields = fields_by_key(&mut *state.db.acquire().await?).await?;
    let mut tx = state.db.begin().await?;

    // ---- bundle-level ----
    if options.bundle_description
        && let Some(body) = archive
            .patch
            .bundle
            .description_md
            .as_deref()
            .map(str::trim)
            .filter(|d| !d.is_empty())
    {
        sqlx::query!(
            "INSERT INTO bundle_description_revisions (bundle_id, body_md, created_by)
             VALUES ($1, $2, $3)",
            bundle_id,
            body,
            user.id,
        )
        .execute(&mut *tx)
        .await?;
    }
    if options.bundle_cover && !cover_images.is_empty() {
        // First cover becomes primary; the rest are added alongside.
        sqlx::query!(
            "UPDATE images SET is_primary = false WHERE bundle_id = $1 AND is_primary",
            bundle_id,
        )
        .execute(&mut *tx)
        .await?;
        for (n, img) in cover_images.iter().enumerate() {
            if insert_image(&mut tx, ImageOwner::Bundle(bundle_id), img, n == 0, user.id).await? {
                result.images_added += 1;
            }
        }
    }

    // The bundle's creator and source page ride along with the scrape. Resolve
    // them once, then fill any matched model that has none of its own — the
    // carve rarely knows either, and "if it has one already, leave it" mirrors
    // how an import stamps a member without clobbering.
    let patch_creator_id = match archive.patch.bundle.creator.as_deref() {
        Some(name) => resolve_creator(&mut tx, name).await?,
        None => None,
    };
    let patch_source_url = archive
        .patch
        .source
        .url
        .as_deref()
        .map(str::trim)
        .filter(|u| !u.is_empty());

    // The scrape *is* this bundle's page, so its creator and source are the
    // bundle's own — replace what the bundle carries (a carve rarely knows
    // either). This is `replace`, not the `fill-if-empty` used for members
    // below: a member can have a creator of its own to protect, the bundle
    // cannot — its creator is whoever the scrape says made it.
    if patch_creator_id.is_some() || patch_source_url.is_some() {
        sqlx::query!(
            r#"UPDATE bundles SET
                 creator_id = coalesce($2::uuid, creator_id),
                 source_url = coalesce($3::text, source_url)
               WHERE id = $1"#,
            bundle_id,
            patch_creator_id,
            patch_source_url,
        )
        .execute(&mut *tx)
        .await?;
    }

    // The bundle's name: the scrape carries the real title, which beats the
    // archive's filename a drop named it after — but only when nobody has
    // renamed it since. A user-chosen name is left alone. The slug follows the
    // new name, keeping its token (see bundles::unique_slug). The flag stays set:
    // a metadata import is not a user, so a better scrape may still correct it.
    if let Some(new_name) = archive
        .patch
        .bundle
        .name
        .as_deref()
        .map(str::trim)
        .filter(|n| !n.is_empty())
    {
        let row = sqlx::query!(
            r#"SELECT name_autogenerated, slug FROM bundles WHERE id = $1"#,
            bundle_id,
        )
        .fetch_one(&mut *tx)
        .await?;
        if row.name_autogenerated {
            let slug = crate::routes::bundles::unique_slug(
                &state,
                new_name,
                Some(&row.slug),
                Some(bundle_id),
            )
            .await?;
            sqlx::query!(
                "UPDATE bundles SET name = $2, slug = $3, updated_at = now() WHERE id = $1",
                bundle_id,
                new_name,
                slug,
            )
            .execute(&mut *tx)
            .await?;
        }
    }

    // ---- per model ----
    for (idx, model_id) in &targets {
        let pm = &archive.patch.models[*idx];
        // The name the model currently carries, for the alias dedup and the
        // "name left behind" a rename records.
        let current_name = members
            .iter()
            .find(|m| m.id == *model_id)
            .map(|m| m.name.as_str())
            .unwrap_or_default();
        let per_model = PerModelOptions {
            rename: options.rename.contains(&idx.to_string()),
            model_tags: options.model_tags,
            model_images: options.model_images,
            model_descriptions: options.model_descriptions,
        };
        apply_model_metadata(
            &mut tx,
            &state,
            &user,
            pm,
            *model_id,
            current_name,
            model_images.get(idx).map(Vec::as_slice).unwrap_or(&[]),
            patch_creator_id,
            patch_source_url,
            &custom_fields,
            per_model,
            &mut result,
        )
        .await?;
    }

    // The bundle's own extra metadata, and the members it reaches from there.
    if !archive.patch.bundle.custom_fields.is_empty() {
        let skipped = apply_patch_values(
            &mut tx,
            &custom_fields,
            ValueOwner::Bundle(bundle_id),
            &archive.patch.bundle.custom_fields,
            &user,
        )
        .await?;
        result.custom_fields_set += archive.patch.bundle.custom_fields.len() - skipped.len();
        persist_bundle_fields(&mut tx, bundle_id, &user).await?;
    }

    tx.commit().await?;
    tracing::info!(
        models = result.models_updated,
        images = result.images_added,
        tags = result.tags_added,
        aliases = result.aliases_added,
        descriptions = result.descriptions_added,
        custom_fields = result.custom_fields_set,
        "patch apply: committed"
    );
    Ok(Json(result))
}

// ---------------------------------------------------------------------------
// Single-model patch: the same scraper zip, but onto one model rather than a
// bundle's members. There is nothing to match — the target is fixed — so the
// only question a multi-model patch raises is *which* patch model to apply, and
// the user answers it. The bundle block contributes only creator/source
// fill-if-empty; its name/cover/description belong to a bundle, and there isn't
// one here.
// ---------------------------------------------------------------------------

#[derive(Serialize, ToSchema)]
struct ModelPatchPreview {
    /// The model's current name — the left side of the rename diff.
    model_name: String,
    /// Whether the model already carries a creator / source URL, so the UI can
    /// say whether the bundle-level values below would actually fill anything.
    model_has_creator: bool,
    model_has_source_url: bool,
    /// The creator and source URL the patch's bundle block carries — stamped onto
    /// the model only where it has none (see the apply). Shown so the fill is not
    /// a surprise.
    bundle_creator: Option<String>,
    bundle_source_url: Option<String>,
    /// One row per model the patch carries; the user picks which applies to this
    /// model (auto-selected when there is only one).
    models: Vec<ModelPatchRow>,
}

#[derive(Serialize, ToSchema)]
struct ModelPatchRow {
    /// The patch model's index — its stable identity, the same in preview and
    /// apply (`model_index`). Names are not unique, so the UI keys on this.
    key: usize,
    patch_name: String,
    /// The tags the patch carries (lowercased); the UI shows which are new once a
    /// target is known (here, always this one model).
    tags: Vec<String>,
    has_image: bool,
    has_description: bool,
    category: Option<String>,
    /// The Creator ID this row would write — it replaces what the model has.
    creator_ref: Option<String>,
    source_url: Option<String>,
    /// Custom field values this row would write onto the model, and the ones it
    /// would skip (each with why — informational, never fatal).
    custom_fields_applied: usize,
    custom_field_warnings: Vec<CustomFieldWarning>,
}

/// Read the single zip a model patch is delivered as — the first `file` part.
/// (`read_upload` already rejects an empty upload.)
async fn read_single(files: Vec<(String, Vec<u8>)>) -> Result<Archive, ApiError> {
    let (name, bytes) = files
        .into_iter()
        .next()
        .ok_or_else(|| ApiError::BadRequest("no file field in upload".into()))?;
    read_archive_from_bytes(bytes).await.map_err(|e| match e {
        ApiError::BadRequest(m) => ApiError::BadRequest(format!("{name}: {m}")),
        other => other,
    })
}

/// Survey one patch model's custom fields against this model: how many would
/// write, and which would be skipped and why. Same primitive the bundle preview
/// uses (`resolve_patch_value`), just for a single fixed owner.
fn survey_model_fields(
    fields: &HashMap<String, CustomField>,
    pm: &PatchModel,
    model_id: Uuid,
) -> (usize, Vec<CustomFieldWarning>) {
    let mut applied = 0;
    let mut warnings = Vec::new();
    let mut keys: Vec<&String> = pm.custom_fields.keys().collect();
    keys.sort();
    for key in keys {
        match resolve_patch_value(
            fields,
            ValueOwner::Model(model_id),
            key,
            &pm.custom_fields[key],
        ) {
            Resolved::Value { .. } => applied += 1,
            Resolved::Warning(reason) => warnings.push(CustomFieldWarning {
                source: pm.label(),
                key: key.clone(),
                reason,
            }),
        }
    }
    (applied, warnings)
}

async fn model_preview(
    State(state): State<AppState>,
    user: User,
    Path(model_id): Path<Uuid>,
    multipart: Multipart,
) -> Result<Json<ModelPatchPreview>, ApiError> {
    let created_by = crate::routes::models::model_created_by(&state, model_id).await?;
    user.require_can_edit(created_by)?;

    let archive = read_single(read_upload(multipart).await?.files).await?;
    let model = sqlx::query!(
        r#"SELECT name,
                  (creator_id IS NOT NULL) as "has_creator!",
                  (source_url IS NOT NULL) as "has_source_url!"
           FROM models WHERE id = $1"#,
        model_id,
    )
    .fetch_one(&state.db)
    .await?;

    let fields = fields_by_key(&mut *state.db.acquire().await?).await?;
    let has_image = |pm: &PatchModel| {
        pm.image_paths()
            .iter()
            .any(|p| archive.images.contains_key(*p))
    };
    let models = archive
        .patch
        .models
        .iter()
        .enumerate()
        .map(|(key, pm)| {
            let (custom_fields_applied, custom_field_warnings) =
                survey_model_fields(&fields, pm, model_id);
            ModelPatchRow {
                key,
                patch_name: pm.label(),
                tags: pm.tags.iter().map(|t| t.to_lowercase()).collect(),
                has_image: has_image(pm),
                has_description: pm
                    .description_md
                    .as_deref()
                    .is_some_and(|d| !d.trim().is_empty()),
                category: pm.category.clone(),
                creator_ref: pm
                    .source_ref
                    .as_deref()
                    .map(str::trim)
                    .filter(|r| !r.is_empty())
                    .map(str::to_string),
                source_url: pm
                    .source_url
                    .as_deref()
                    .map(str::trim)
                    .filter(|u| !u.is_empty())
                    .map(str::to_string),
                custom_fields_applied,
                custom_field_warnings,
            }
        })
        .collect();

    Ok(Json(ModelPatchPreview {
        model_name: model.name,
        model_has_creator: model.has_creator,
        model_has_source_url: model.has_source_url,
        bundle_creator: archive
            .patch
            .bundle
            .creator
            .as_deref()
            .map(str::trim)
            .filter(|c| !c.is_empty())
            .map(str::to_string),
        bundle_source_url: archive
            .patch
            .source
            .url
            .as_deref()
            .map(str::trim)
            .filter(|u| !u.is_empty())
            .map(str::to_string),
        models,
    }))
}

#[derive(Deserialize, Default)]
struct ModelApplyOptions {
    /// Which of the patch's models to apply to this one — its `key` from the
    /// preview. Defaults to the first, which is the only one for a single-model
    /// patch (the common case, where the UI need not ask).
    #[serde(default)]
    model_index: usize,
    /// Rename this model to the chosen patch model's name.
    #[serde(default)]
    rename: bool,
    #[serde(default)]
    model_tags: TagMode,
    #[serde(default)]
    model_images: ImageMode,
    #[serde(default)]
    model_descriptions: bool,
}

#[tracing::instrument(skip_all, fields(model = %model_id))]
async fn model_apply(
    State(state): State<AppState>,
    user: User,
    Path(model_id): Path<Uuid>,
    multipart: Multipart,
) -> Result<Json<ApplyResult>, ApiError> {
    let created_by = crate::routes::models::model_created_by(&state, model_id).await?;
    user.require_can_edit(created_by)?;

    let upload = read_upload(multipart).await?;
    let options: ModelApplyOptions = match upload.options.as_deref() {
        Some(text) => serde_json::from_str(text)
            .map_err(|e| ApiError::BadRequest(format!("bad options: {e}")))?,
        None => ModelApplyOptions::default(),
    };
    let archive = read_single(upload.files).await?;

    let pm = archive
        .patch
        .models
        .get(options.model_index)
        .ok_or_else(|| {
            ApiError::BadRequest(format!(
                "the patch has no model at index {} (it carries {})",
                options.model_index,
                archive.patch.models.len()
            ))
        })?;

    // Put image blobs before opening the transaction — a blob put is async
    // filesystem work, and a rollback must not have to un-write the store.
    let mut staged_images = Vec::new();
    if options.model_images != ImageMode::Skip {
        for path in pm.image_paths() {
            if let Some(staged) = stage_image(&state, &archive.images, path).await? {
                staged_images.push(staged);
            }
        }
    }

    let custom_fields = fields_by_key(&mut *state.db.acquire().await?).await?;
    let mut result = ApplyResult::default();
    let mut tx = state.db.begin().await?;

    // The bundle block's creator/source fill this model where it has none, the
    // same fill-if-empty stamp a bundle patch gives its members.
    let patch_creator_id = match archive.patch.bundle.creator.as_deref() {
        Some(name) => resolve_creator(&mut tx, name).await?,
        None => None,
    };
    let patch_source_url = archive
        .patch
        .source
        .url
        .as_deref()
        .map(str::trim)
        .filter(|u| !u.is_empty());

    let current_name = sqlx::query_scalar!("SELECT name FROM models WHERE id = $1", model_id)
        .fetch_one(&mut *tx)
        .await?;

    apply_model_metadata(
        &mut tx,
        &state,
        &user,
        pm,
        model_id,
        &current_name,
        &staged_images,
        patch_creator_id,
        patch_source_url,
        &custom_fields,
        PerModelOptions {
            rename: options.rename,
            model_tags: options.model_tags,
            model_images: options.model_images,
            model_descriptions: options.model_descriptions,
        },
        &mut result,
    )
    .await?;

    tx.commit().await?;
    Ok(Json(result))
}

/// How to apply one patch model's metadata onto its target — the subset of the
/// apply options that is per-model rather than per-request.
struct PerModelOptions {
    /// Rename the target to the patch's `name` (slug follows).
    rename: bool,
    model_tags: TagMode,
    model_images: ImageMode,
    model_descriptions: bool,
}

/// Merge one `PatchModel`'s metadata onto one library model, inside the caller's
/// transaction. This is the whole per-model half of a patch apply — the bundle
/// apply runs it once per matched member, the single-model apply runs it once for
/// the model the user picked, so the merge rules (creator/source fill-if-empty,
/// own source_url/creator_ref replace, opt-in rename, tag merge/replace/skip,
/// description-as-revision with dedup, image replace/add/skip, alias recording,
/// custom fields) live in exactly one place.
///
/// `current_name` is the model's name as it stands now: the fallback for the
/// alias dedup and the name a rename leaves behind. Counters accumulate into
/// `result`, and a model that changed anything bumps `models_updated`.
#[allow(clippy::too_many_arguments)]
async fn apply_model_metadata(
    tx: &mut sqlx::PgConnection,
    state: &AppState,
    user: &User,
    pm: &PatchModel,
    model_id: Uuid,
    current_name: &str,
    staged_images: &[StagedImage],
    patch_creator_id: Option<Uuid>,
    patch_source_url: Option<&str>,
    custom_fields: &HashMap<String, CustomField>,
    options: PerModelOptions,
    result: &mut ApplyResult,
) -> Result<(), ApiError> {
    let mut touched = false;

    // Stamp the bundle's creator/source onto the model, but only where it has
    // none — coalesce keeps whatever the model already knows, and the WHERE
    // means an all-already-set model reports no change.
    if patch_creator_id.is_some() || patch_source_url.is_some() {
        let filled = sqlx::query!(
            r#"UPDATE models SET
                 creator_id = coalesce(creator_id, $2::uuid),
                 source_url = coalesce(source_url, $3::text)
               WHERE id = $1
                 AND (($2::uuid IS NOT NULL AND creator_id IS NULL)
                   OR ($3::text IS NOT NULL AND source_url IS NULL))"#,
            model_id,
            patch_creator_id,
            patch_source_url,
        )
        .execute(&mut *tx)
        .await?;
        if filled.rows_affected() > 0 {
            touched = true;
        }
    }

    // The model's *own* page, when the scrape has one. Unlike the bundle's
    // URL above this replaces: `source.url` is a fill-if-empty guess (the
    // bundle's page stamped on a member for want of anything better), while
    // this is the page that model was actually scraped from, so a re-scrape
    // should be able to correct a URL an earlier one guessed.
    if let Some(url) = pm
        .source_url
        .as_deref()
        .map(str::trim)
        .filter(|u| !u.is_empty())
    {
        let set = sqlx::query!(
            r#"UPDATE models SET source_url = $2
               WHERE id = $1 AND source_url IS DISTINCT FROM $2"#,
            model_id,
            url,
        )
        .execute(&mut *tx)
        .await?;
        if set.rows_affected() > 0 {
            touched = true;
        }
    }

    // The creator's own id/SKU (`models.creator_ref`, shown as "Creator ID").
    //
    // **Replaces**, like `source_url` and for the same reason: the shop page
    // is the authority on the shop's own product code, and a re-scrape
    // should be able to correct one an earlier pass got wrong. The other
    // filler of this column is a carve layout's `creator_ref` capture group,
    // which read it off a folder name — a name that may well be a truncation
    // of the real code, so deferring to it would be deferring to the weaker
    // source. Blank/whitespace is absent, and clears nothing.
    if let Some(reference) = pm
        .source_ref
        .as_deref()
        .map(str::trim)
        .filter(|r| !r.is_empty())
    {
        let set = sqlx::query!(
            r#"UPDATE models SET creator_ref = $2
               WHERE id = $1 AND creator_ref IS DISTINCT FROM $2"#,
            model_id,
            reference,
        )
        .execute(&mut *tx)
        .await?;
        if set.rows_affected() > 0 {
            result.creator_refs_set += 1;
            touched = true;
        }
    }

    let renamed_to = if options.rename {
        pm.name.as_deref().map(str::trim).filter(|n| !n.is_empty())
    } else {
        None
    };
    if let Some(name) = renamed_to {
        // The slug follows the name, like the model editor and the bundle
        // rename above: regenerate it from the new name, carrying the current
        // slug's token so the URL keeps its identity and old slugs/the UUID
        // still redirect. Without this the slug stayed stale — "Bayul" kept
        // `bayul-<token>` after being renamed to "Bayul Greytusk".
        let current_slug = sqlx::query_scalar!("SELECT slug FROM models WHERE id = $1", model_id)
            .fetch_one(&mut *tx)
            .await?;
        let slug =
            crate::routes::models::unique_slug(state, name, Some(&current_slug), Some(model_id))
                .await?;
        sqlx::query!(
            "UPDATE models SET name = $2, slug = $3 WHERE id = $1",
            model_id,
            name,
            slug,
        )
        .execute(&mut *tx)
        .await?;
        touched = true;
    }

    if options.model_tags != TagMode::Skip && !pm.tags.is_empty() {
        if options.model_tags == TagMode::Replace {
            sqlx::query!("DELETE FROM model_tags WHERE model_id = $1", model_id)
                .execute(&mut *tx)
                .await?;
        }
        for name in &pm.tags {
            let tag = upsert_tag(&mut *tx, name).await?;
            let added = sqlx::query!(
                "INSERT INTO model_tags (model_id, tag_id) VALUES ($1, $2)
                 ON CONFLICT DO NOTHING",
                model_id,
                tag.id,
            )
            .execute(&mut *tx)
            .await?;
            result.tags_added += added.rows_affected() as usize;
        }
        touched = true;
    }

    // A model description becomes a revision, like every description edit
    // (newest = current, history kept) — but only when it would change
    // something: re-applying the same patch must not stack duplicate
    // revisions the way it must not re-add tags or images.
    if options.model_descriptions
        && let Some(body) = pm
            .description_md
            .as_deref()
            .map(str::trim)
            .filter(|d| !d.is_empty())
    {
        let current = sqlx::query_scalar!(
            "SELECT body_md FROM model_description_revisions
             WHERE model_id = $1 ORDER BY created_at DESC LIMIT 1",
            model_id,
        )
        .fetch_optional(&mut *tx)
        .await?;
        if current.as_deref() != Some(body) {
            sqlx::query!(
                "INSERT INTO model_description_revisions (model_id, body_md, created_by)
                 VALUES ($1, $2, $3)",
                model_id,
                body,
                user.id,
            )
            .execute(&mut *tx)
            .await?;
            result.descriptions_added += 1;
            touched = true;
        }
    }

    if !staged_images.is_empty() {
        if options.model_images == ImageMode::ReplaceGenerated {
            // The auto previews live on the model's variants (and, rarely, the
            // model). Drop them so the scraped image is what shows.
            sqlx::query!(
                "DELETE FROM images WHERE kind = 'rendered' AND (model_id = $1
                   OR variant_id IN (SELECT id FROM model_variants WHERE model_id = $1))",
                model_id,
            )
            .execute(&mut *tx)
            .await?;
        }
        sqlx::query!(
            "UPDATE images SET is_primary = false WHERE model_id = $1 AND is_primary",
            model_id,
        )
        .execute(&mut *tx)
        .await?;
        // First is primary, the rest ride along — the same rule as
        // `bundle.images`. Deduped by content hash inside insert_image, so
        // re-applying a patch adds nothing.
        for (n, img) in staged_images.iter().enumerate() {
            if insert_image(&mut *tx, ImageOwner::Model(model_id), img, n == 0, user.id).await? {
                result.images_added += 1;
            }
        }
        touched = true;
    }

    // ---- aliases ----
    // Teach the model every name this scrape knows it by, so a later import
    // resolves it outright instead of falling back to a fuzzy match; a rename
    // also records the name being left behind. citext + the (model, alias)
    // key dedup case variants; we drop any that just repeat the model's own
    // (final) name.
    let final_name = renamed_to.unwrap_or(current_name);
    let mut aliases: Vec<&str> = pm.match_hint.aliases.iter().map(String::as_str).collect();
    if renamed_to.is_some() {
        aliases.push(current_name);
    }
    // Rename declined: the name it would have taken is still a name this scrape
    // knows the model by. Record it as an alias so a later import recognises the
    // model by it and doesn't re-offer the rename. (When the rename was applied,
    // pm.name is the new name and the dedup below drops it — hence the guard.)
    if renamed_to.is_none()
        && let Some(name) = pm.name.as_deref()
    {
        aliases.push(name);
    }
    for alias in aliases {
        let alias = alias.trim();
        if alias.is_empty() || alias.eq_ignore_ascii_case(final_name) {
            continue;
        }
        let added = sqlx::query!(
            "INSERT INTO model_aliases (model_id, alias) VALUES ($1, $2) ON CONFLICT DO NOTHING",
            model_id,
            alias,
        )
        .execute(&mut *tx)
        .await?;
        if added.rows_affected() > 0 {
            result.aliases_added += 1;
            touched = true;
        }
    }

    // Scraped extra metadata. An unknown or inapplicable key was already
    // reported as a warning by the preview; here it is simply skipped.
    if !pm.custom_fields.is_empty() {
        let skipped = apply_patch_values(
            &mut *tx,
            custom_fields,
            ValueOwner::Model(model_id),
            &pm.custom_fields,
            user,
        )
        .await?;
        if pm.custom_fields.len() > skipped.len() {
            result.custom_fields_set += pm.custom_fields.len() - skipped.len();
            touched = true;
        }
    }

    if touched {
        result.models_updated += 1;
    }
    Ok(())
}

enum ImageOwner {
    Model(Uuid),
    Bundle(Uuid),
}

/// Insert an image for an owner from an already-staged blob, deduped: if the
/// owner already carries that exact blob, only its primary flag is touched.
/// Returns whether a new row was inserted.
async fn insert_image(
    tx: &mut sqlx::PgConnection,
    owner: ImageOwner,
    img: &StagedImage,
    primary: bool,
    user_id: Uuid,
) -> Result<bool, ApiError> {
    let (model_id, bundle_id) = match owner {
        ImageOwner::Model(id) => (Some(id), None),
        ImageOwner::Bundle(id) => (None, Some(id)),
    };
    sqlx::query!(
        "INSERT INTO blobs (sha256, size) VALUES ($1, $2) ON CONFLICT DO NOTHING",
        img.sha256,
        img.size,
    )
    .execute(&mut *tx)
    .await?;
    let inserted = sqlx::query!(
        r#"INSERT INTO images (blob_sha256, model_id, bundle_id, kind, mime, is_primary, created_by)
           SELECT $1, $2, $3, 'imported', $4, $5, $6
           WHERE NOT EXISTS (
               SELECT 1 FROM images i
               WHERE i.blob_sha256 = $1
                 AND ((i.model_id = $2 AND $2 IS NOT NULL)
                   OR (i.bundle_id = $3 AND $3 IS NOT NULL)))"#,
        img.sha256,
        model_id,
        bundle_id,
        img.mime,
        primary,
        user_id,
    )
    .execute(&mut *tx)
    .await?;
    if inserted.rows_affected() == 0 && primary {
        // Already present — just make sure it is the primary one.
        sqlx::query!(
            "UPDATE images SET is_primary = true
             WHERE blob_sha256 = $1
               AND ((model_id = $2 AND $2 IS NOT NULL) OR (bundle_id = $3 AND $3 IS NOT NULL))",
            img.sha256,
            model_id,
            bundle_id,
        )
        .execute(&mut *tx)
        .await?;
    }
    Ok(inserted.rows_affected() > 0)
}

/// Scraped metadata arrives HTML-encoded — a title with an en dash comes through
/// as `&#8211;`, an ampersand as `&amp;`. Decode entities on the way in so stored
/// names, descriptions, creators, and tags read as text rather than markup. Image
/// references are left untouched: they must match zip entry names byte for byte.
fn decode_entities(patch: &mut Patch) {
    fn dec(s: &mut Option<String>) {
        if let Some(v) = s {
            *v = html_escape::decode_html_entities(v).into_owned();
        }
    }
    fn dec_all(v: &mut [String]) {
        for s in v {
            *s = html_escape::decode_html_entities(s).into_owned();
        }
    }
    /// Custom field values, where they are text. A choice field's value has to
    /// match one of its defined choices *exactly*, so an undecoded "Black &amp;
    /// White" would be rejected as "not one of this field's choices" — the
    /// entity has to go before the value is ever compared. Keys are left alone:
    /// they are slugs by construction (letters, digits, `-`, `_`), so there is
    /// nothing in one to decode.
    fn dec_values(map: &mut HashMap<String, serde_json::Value>) {
        for value in map.values_mut() {
            if let serde_json::Value::String(s) = value {
                *s = html_escape::decode_html_entities(s).into_owned();
            }
        }
    }
    dec(&mut patch.source.url);
    dec(&mut patch.bundle.name);
    dec(&mut patch.bundle.creator);
    dec(&mut patch.bundle.description_md);
    dec_values(&mut patch.bundle.custom_fields);
    for m in &mut patch.models {
        dec(&mut m.name);
        dec(&mut m.category);
        dec(&mut m.description_md);
        dec(&mut m.source_url);
        dec(&mut m.source_ref);
        dec_all(&mut m.tags);
        dec(&mut m.match_hint.name);
        dec_all(&mut m.match_hint.aliases);
        dec_values(&mut m.custom_fields);
    }
}

async fn read_archive_from_bytes(bytes: Vec<u8>) -> Result<Archive, ApiError> {
    tokio::task::spawn_blocking(move || {
        let mut zip = zip::ZipArchive::new(Cursor::new(bytes))
            .map_err(|e| ApiError::BadRequest(format!("not a zip: {e}")))?;
        let mut patch_json: Option<Vec<u8>> = None;
        let mut images = HashMap::new();
        for i in 0..zip.len() {
            let mut entry = zip
                .by_index(i)
                .map_err(|e| ApiError::BadRequest(format!("bad zip entry: {e}")))?;
            let Some(name) = entry
                .enclosed_name()
                .map(|p| p.to_string_lossy().to_string())
            else {
                continue;
            };
            if !entry.is_file() {
                continue;
            }
            let mut buf = Vec::new();
            entry
                .read_to_end(&mut buf)
                .map_err(|e| ApiError::BadRequest(format!("reading {name}: {e}")))?;
            if name == "patch.json" || name.ends_with("/patch.json") {
                patch_json = Some(buf);
            } else {
                images.insert(name, buf);
            }
        }
        let patch_json =
            patch_json.ok_or_else(|| ApiError::BadRequest("no patch.json in the zip".into()))?;
        let mut patch: Patch = serde_json::from_slice(&patch_json)
            .map_err(|e| ApiError::BadRequest(format!("bad patch.json: {e}")))?;
        decode_entities(&mut patch);
        Ok(Archive { patch, images })
    })
    .await
    .map_err(|e| ApiError::Internal(e.into()))?
}

/// Resolve a creator name to a `creators` row, reusing an existing one
/// (case-insensitively) or creating it. `creators.name` has no unique index, so
/// this is a find-then-insert rather than an upsert; a blank name resolves to
/// nothing. Runs inside the caller's transaction.
async fn resolve_creator(
    tx: &mut sqlx::PgConnection,
    name: &str,
) -> Result<Option<Uuid>, ApiError> {
    let name = name.trim();
    if name.is_empty() {
        return Ok(None);
    }
    if let Some(id) = sqlx::query_scalar!(
        "SELECT id FROM creators WHERE lower(name) = lower($1) ORDER BY created_at LIMIT 1",
        name,
    )
    .fetch_optional(&mut *tx)
    .await?
    {
        return Ok(Some(id));
    }
    let id = sqlx::query_scalar!("INSERT INTO creators (name) VALUES ($1) RETURNING id", name)
        .fetch_one(&mut *tx)
        .await?;
    Ok(Some(id))
}

async fn bundle_created_by(state: &AppState, bundle_id: Uuid) -> Result<Uuid, ApiError> {
    sqlx::query_scalar!("SELECT created_by FROM bundles WHERE id = $1", bundle_id)
        .fetch_optional(&state.db)
        .await?
        .ok_or(ApiError::NotFound)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn member(name: &str, tags: &[&str]) -> Member {
        Member {
            id: Uuid::new_v4(),
            name: name.into(),
            tags: tags.iter().map(|t| t.to_string()).collect(),
            aliases: Vec::new(),
        }
    }

    fn member_with_aliases(name: &str, aliases: &[&str]) -> Member {
        Member {
            id: Uuid::new_v4(),
            name: name.into(),
            tags: Vec::new(),
            aliases: aliases.iter().map(|a| a.to_string()).collect(),
        }
    }

    /// A patch model that matches on `scraped` (its scrape name), with a category.
    fn pm(scraped: &str, category: Option<&str>) -> PatchModel {
        PatchModel {
            uuid: None,
            match_hint: MatchHint {
                name: Some(scraped.into()),
                aliases: Vec::new(),
            },
            name: None,
            tags: Vec::new(),
            description_md: None,
            image: None,
            images: Vec::new(),
            category: category.map(str::to_string),
            source_url: None,
            source_ref: None,
            custom_fields: HashMap::new(),
        }
    }

    fn resolve_one(pm: PatchModel, members: &[Member]) -> Vec<Uuid> {
        let patch = Patch {
            source: PatchSource::default(),
            bundle: PatchBundle::default(),
            models: vec![pm],
        };
        resolve(&patch, members).pop().unwrap()
    }

    #[test]
    fn uuid_matches_directly_and_beats_names() {
        let members = [member("Crocodile", &[]), member("Camel", &[])];
        let mut p = pm("Camel", None); // the name says Camel…
        p.uuid = Some(members[0].id); // …the uuid says Crocodile; the uuid wins
        assert_eq!(resolve_one(p, &members), vec![members[0].id]);
    }

    #[test]
    fn unknown_uuid_matches_nothing_rather_than_falling_back() {
        // The id says the scraper meant one specific model; if it isn't a
        // member here, guessing by name would be exactly the mistake an id is
        // there to prevent.
        let members = [member("Camel", &[])];
        let mut p = pm("Camel", None);
        p.uuid = Some(Uuid::new_v4());
        assert!(resolve_one(p, &members).is_empty());
    }

    #[test]
    fn blank_or_absent_uuid_reads_as_none() {
        let p: PatchModel = serde_json::from_str(r#"{"uuid": "", "name": "Camel"}"#).unwrap();
        assert!(p.uuid.is_none());
        let p: PatchModel = serde_json::from_str(r#"{"uuid": null, "name": "Camel"}"#).unwrap();
        assert!(p.uuid.is_none());
        let p: PatchModel = serde_json::from_str(r#"{"name": "Camel"}"#).unwrap();
        assert!(p.uuid.is_none());
        assert!(serde_json::from_str::<PatchModel>(r#"{"uuid": "not-a-uuid"}"#).is_err());
    }

    #[test]
    fn exact_collapsed_name_still_matches() {
        let members = [member("AdvisorMummy", &[])];
        assert_eq!(
            resolve_one(pm("Advisor Mummy", None), &members),
            vec![members[0].id]
        );
    }

    #[test]
    fn prefix_match_ignores_trailing_bundle_words() {
        // The reported case: "Crocodile Buried Tomb" carries the bundle name, and
        // there is only one Crocodile, so it matches with no ambiguity.
        let members = [member("Crocodile", &[]), member("Camel", &[])];
        assert_eq!(
            resolve_one(pm("Crocodile Buried Tomb", Some("Enemies")), &members),
            vec![members[0].id]
        );
    }

    #[test]
    fn prefix_is_ordered_not_a_loose_substring() {
        // "Mummy" is inside the scraped name but not its leading run, so it is not
        // a prefix match — only the model that actually leads matches.
        let members = [member("Mummy", &[]), member("WarriorMummy", &[])];
        assert_eq!(
            resolve_one(pm("Warrior Mummy Buried Tomb", None), &members),
            vec![members[1].id]
        );
    }

    #[test]
    fn longest_prefix_wins_over_a_shorter_one() {
        let members = [member("Warrior", &[]), member("WarriorMummy", &[])];
        assert_eq!(
            resolve_one(pm("Warrior Mummy Buried Tomb", None), &members),
            vec![members[1].id]
        );
    }

    #[test]
    fn category_breaks_a_tie_among_equal_length_prefixes() {
        // Two same-named models, told apart only by the category they came from.
        let members = [member("Gold", &["Enemies"]), member("Gold", &["Bonus"])];
        assert_eq!(
            resolve_one(pm("Gold Buried Tomb", Some("Bonus")), &members),
            vec![members[1].id]
        );
    }

    #[test]
    fn category_that_no_candidate_carries_leaves_the_tie() {
        // The category must not wipe out an otherwise-good set: with neither Gold
        // tagged NPCs, both stay and the user picks.
        let members = [member("Gold", &["Enemies"]), member("Gold", &["Bonus"])];
        let got = resolve_one(pm("Gold Buried Tomb", Some("NPCs")), &members);
        assert_eq!(got.len(), 2);
    }

    #[test]
    fn single_prefix_matches_without_a_category_tag() {
        // Crocodile carries no category tag at all; a lone prefix still matches.
        let members = [member("Crocodile", &["32mm", "tomb"])];
        assert_eq!(
            resolve_one(pm("Crocodile Buried Tomb", Some("Enemies")), &members),
            vec![members[0].id]
        );
    }

    #[test]
    fn no_prefix_is_no_match() {
        let members = [member("Crocodile", &[]), member("Camel", &[])];
        assert!(resolve_one(pm("Dragon Buried Tomb", None), &members).is_empty());
    }

    #[test]
    fn a_stored_alias_gives_an_exact_match() {
        let members = [member_with_aliases(
            "WerejackalPriest_V2",
            &["Werejackal Priest"],
        )];
        assert_eq!(
            resolve_one(pm("Werejackal Priest", None), &members),
            vec![members[0].id]
        );
    }

    #[test]
    fn a_stored_alias_participates_in_the_prefix_fallback() {
        // The reported case: a versioned member the bare name would miss. Its alias
        // "Werejackal Priest" leads the scraped name, and being the longer spelling
        // it wins over a plain "Werejackal".
        let members = [
            member_with_aliases("WerejackalPriest_V2", &["Werejackal Priest"]),
            member("Werejackal", &[]),
        ];
        assert_eq!(
            resolve_one(pm("Werejackal Priest Buried Tomb", None), &members),
            vec![members[0].id]
        );
    }

    #[test]
    fn image_paths_puts_the_singular_first_and_dedupes() {
        // A scraper that keeps `image` populated for older consumers *and* sends
        // the same file as images[0] must not contribute it twice — the first
        // entry becomes primary, and a duplicate would just churn the flag.
        let p: PatchModel =
            serde_json::from_str(r#"{"image": "a.png", "images": ["a.png", "b.png", "c.png"]}"#)
                .unwrap();
        assert_eq!(p.image_paths(), vec!["a.png", "b.png", "c.png"]);
    }

    #[test]
    fn image_paths_handles_each_field_alone() {
        let only_singular: PatchModel = serde_json::from_str(r#"{"image": "a.png"}"#).unwrap();
        assert_eq!(only_singular.image_paths(), vec!["a.png"]);
        let only_plural: PatchModel = serde_json::from_str(r#"{"images": ["a.png"]}"#).unwrap();
        assert_eq!(only_plural.image_paths(), vec!["a.png"]);
        let neither: PatchModel = serde_json::from_str(r#"{}"#).unwrap();
        assert!(neither.image_paths().is_empty());
    }

    #[test]
    fn decode_entities_decodes_names_tags_and_description() {
        let mut patch = Patch {
            source: PatchSource {
                url: Some("https://x.test/?a=1&amp;b=2".into()),
            },
            bundle: PatchBundle {
                name: Some("Tomb &#8211; Kickstarter".into()),
                creator: Some("Bob &amp; Co".into()),
                description_md: Some("Isn&#39;t it grand".into()),
                images: vec!["cover&#8211;.png".into()],
                custom_fields: HashMap::from([
                    ("material".into(), serde_json::json!("Black &amp; White")),
                    ("printed".into(), serde_json::json!(true)),
                ]),
            },
            models: vec![PatchModel {
                uuid: None,
                match_hint: MatchHint {
                    name: Some("Crocodile &amp; Camel".into()),
                    aliases: vec!["Croc &#8211; v2".into()],
                },
                name: Some("Crocodile &#8211; Buried".into()),
                tags: vec!["large &amp; scaly".into()],
                description_md: Some("A croc &amp; his tomb".into()),
                image: Some("model&#8211;.png".into()),
                images: vec!["gallery&#8211;.png".into()],
                category: Some("Enemies &amp; Foes".into()),
                source_url: Some("https://x.test/p?a=1&amp;b=2".into()),
                source_ref: Some("FDG&#8211;0250".into()),
                custom_fields: HashMap::from([(
                    "notes".into(),
                    serde_json::json!("supports &#8211; 45&#176;"),
                )]),
            }],
        };
        decode_entities(&mut patch);
        assert_eq!(patch.source.url.as_deref(), Some("https://x.test/?a=1&b=2"));
        assert_eq!(patch.bundle.name.as_deref(), Some("Tomb – Kickstarter"));
        assert_eq!(patch.bundle.creator.as_deref(), Some("Bob & Co"));
        assert_eq!(
            patch.bundle.description_md.as_deref(),
            Some("Isn't it grand")
        );
        assert_eq!(patch.models[0].name.as_deref(), Some("Crocodile – Buried"));
        assert_eq!(patch.models[0].tags, vec!["large & scaly"]);
        assert_eq!(
            patch.models[0].description_md.as_deref(),
            Some("A croc & his tomb")
        );
        assert_eq!(patch.models[0].category.as_deref(), Some("Enemies & Foes"));
        assert_eq!(
            patch.models[0].match_hint.name.as_deref(),
            Some("Crocodile & Camel")
        );
        assert_eq!(patch.models[0].match_hint.aliases, vec!["Croc – v2"]);
        assert_eq!(patch.models[0].source_ref.as_deref(), Some("FDG–0250"));
        // A text custom field value is text like any other — a choice value has
        // to match its defined choice exactly, and non-strings are untouched.
        assert_eq!(
            patch.bundle.custom_fields["material"],
            serde_json::json!("Black & White")
        );
        assert_eq!(
            patch.bundle.custom_fields["printed"],
            serde_json::json!(true)
        );
        assert_eq!(
            patch.models[0].custom_fields["notes"],
            serde_json::json!("supports – 45°")
        );
        // Image references stay byte-for-byte so they still match zip entries.
        assert_eq!(patch.bundle.images, vec!["cover&#8211;.png"]);
        assert_eq!(patch.models[0].image.as_deref(), Some("model&#8211;.png"));
        assert_eq!(patch.models[0].images, vec!["gallery&#8211;.png"]);
    }

    /// Build a one-model patch zip in memory: `patch.json` plus one image, both
    /// at paths a real scraper would use — the collision this merge has to
    /// survive is that every scraper independently calls its first image
    /// `images/00.jpg`.
    fn zip_of(model: &str, creator: Option<&str>, image: &[u8]) -> Vec<u8> {
        use std::io::Write;
        use zip::write::SimpleFileOptions;

        let bundle = match creator {
            Some(c) => format!(r#"{{"creator":"{c}"}}"#),
            None => "{}".to_string(),
        };
        let doc = format!(
            r#"{{"schema":"meshtrove.bundle-patch/1","bundle":{bundle},
                 "models":[{{"match":{{"name":"{model}"}},"name":"{model}",
                             "image":"images/00.jpg","images":["images/00.jpg"]}}]}}"#
        );
        let mut w = zip::ZipWriter::new(Cursor::new(Vec::new()));
        let opts = SimpleFileOptions::default();
        w.start_file("patch.json", opts).unwrap();
        w.write_all(doc.as_bytes()).unwrap();
        w.start_file("images/00.jpg", opts).unwrap();
        w.write_all(image).unwrap();
        w.finish().unwrap().into_inner()
    }

    /// Several per-model patches merge into one, which is what lets a drop of
    /// six product-page zips behave like one six-model patch.
    #[tokio::test]
    async fn several_patch_files_merge_into_one() {
        // Handed over in the wrong order on purpose: ordering is by filename, so
        // that `key` means the same thing here as in the matching apply call.
        let files = vec![
            ("b.zip".to_string(), zip_of("Beta", None, b"BBBB")),
            (
                "a.zip".to_string(),
                zip_of("Alpha", Some("Fat Dragon"), b"AAAA"),
            ),
        ];
        let (merged, rows) = read_merged(files).await.unwrap();

        assert_eq!(
            rows.iter().map(|r| r.name.as_str()).collect::<Vec<_>>(),
            ["a.zip", "b.zip"],
            "files are ordered by name, not by arrival"
        );
        assert_eq!(
            merged
                .patch
                .models
                .iter()
                .map(|m| m.name.as_deref().unwrap())
                .collect::<Vec<_>>(),
            ["Alpha", "Beta"],
            "models concatenate in file order, so key is the merged index"
        );
        // Both files called their image `images/00.jpg`. Namespacing keeps both
        // blobs, and each model's reference must still resolve to its own.
        assert_eq!(merged.images.len(), 2, "neither image was overwritten");
        let alpha = merged.patch.models[0].image.as_deref().unwrap();
        let beta = merged.patch.models[1].image.as_deref().unwrap();
        assert_ne!(alpha, beta);
        assert_eq!(
            merged.images.get(alpha).map(Vec::as_slice),
            Some(&b"AAAA"[..])
        );
        assert_eq!(
            merged.images.get(beta).map(Vec::as_slice),
            Some(&b"BBBB"[..])
        );
        // `images` is rewritten alongside `image`, or apply drops the gallery.
        assert_eq!(merged.patch.models[0].images, vec![alpha.to_string()]);
        // Bundle fields are first-non-empty wins, and "first" is by sorted name
        // — a.zip supplies the creator even though it arrived second.
        assert_eq!(merged.patch.bundle.creator.as_deref(), Some("Fat Dragon"));
    }

    /// One file in is one archive out: merging must not change what a single
    /// patch means, since that is every existing caller.
    #[tokio::test]
    async fn a_single_file_is_unchanged_by_the_merge() {
        let files = vec![("only.zip".to_string(), zip_of("Solo", Some("Bob"), b"X"))];
        let (merged, rows) = read_merged(files).await.unwrap();
        assert_eq!(rows.len(), 1);
        assert_eq!(merged.patch.models.len(), 1);
        assert_eq!(merged.patch.bundle.creator.as_deref(), Some("Bob"));
        let path = merged.patch.models[0].image.as_deref().unwrap();
        assert_eq!(merged.images.get(path).map(Vec::as_slice), Some(&b"X"[..]));
    }

    /// A bad zip in a six-file drop has to name itself, or there is no way to
    /// tell which one to fix.
    #[tokio::test]
    async fn a_broken_file_in_the_batch_names_itself() {
        let files = vec![
            ("good.zip".to_string(), zip_of("Alpha", None, b"A")),
            ("broken.zip".to_string(), b"not a zip at all".to_vec()),
        ];
        // Not `unwrap_err`: that wants Debug on the Ok type, and an Archive
        // holds every image byte — deriving it to print on failure would be a
        // megabyte of hex.
        match read_merged(files).await {
            Err(ApiError::BadRequest(msg)) => {
                assert!(msg.starts_with("broken.zip: "), "got {msg:?}")
            }
            Err(other) => panic!("expected a bad-request, got {other:?}"),
            Ok(_) => panic!("expected the broken zip to fail the whole merge"),
        }
    }

    /// A single-model patch takes one zip; the reader names a bad one so the
    /// error points at the file, the same courtesy the multi-zip merge gives.
    #[tokio::test]
    async fn read_single_reads_one_zip_and_names_a_bad_one() {
        let (archive, _) = read_merged(vec![("only.zip".into(), zip_of("Solo", None, b"X"))])
            .await
            .unwrap();
        assert_eq!(archive.patch.models.len(), 1);

        match read_single(vec![("bad.zip".into(), b"nope".to_vec())]).await {
            Err(ApiError::BadRequest(msg)) => assert!(msg.starts_with("bad.zip: "), "got {msg:?}"),
            Err(other) => panic!("expected a bad-request, got {other:?}"),
            Ok(_) => panic!("expected the broken zip to fail"),
        }
    }

    /// The apply options default to "apply the only model, merge, replace the
    /// render" — so a single-model patch needs no options at all, and `key`
    /// (the preview's row id) is the `model_index` the apply selects by.
    #[test]
    fn model_apply_options_default_and_parse() {
        let d: ModelApplyOptions = serde_json::from_str("{}").unwrap();
        assert_eq!(d.model_index, 0);
        assert!(!d.rename);
        assert_eq!(d.model_tags, TagMode::Merge);
        assert_eq!(d.model_images, ImageMode::ReplaceGenerated);
        assert!(!d.model_descriptions);

        let o: ModelApplyOptions = serde_json::from_str(
            r#"{"model_index":2,"rename":true,"model_tags":"replace",
                "model_images":"add","model_descriptions":true}"#,
        )
        .unwrap();
        assert_eq!(o.model_index, 2);
        assert!(o.rename);
        assert_eq!(o.model_tags, TagMode::Replace);
        assert_eq!(o.model_images, ImageMode::Add);
        assert!(o.model_descriptions);
    }
}
